import Head from 'next/head'
import Image from 'next/image';
import cogumelo from './images/cogumelo.jpeg'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="container">
        <h1>Estamos aprendendo Next com o melhor professor de todos</h1>
        <div class="lista-cogumelos">
          <div class='cogumelo'>
            <Image
              src={cogumelo}
              alt="cogumelo"
              width={180}
              height={100}
              className='cogumeloHome'
            />
            <p> cogumelo 1</p>
          </div>
          <div class='cogumelo'>
            <Image
              src={cogumelo}
              alt="cogumelo"
              width={180}
              height={100}
              className='cogumeloHome'
            />
            <p> cogumelo 2</p>
          </div>
          <div class='cogumelo'>
            <Image
              src={cogumelo}
              alt="cogumelo"
              width={180}
              height={100}
              className='cogumeloHome'
            />
            <p> cogumelo 3</p>
          </div>
         
        </div>

        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Neque maxime voluptatem at ipsa quaerat tempore, necessitatibus reiciendis aspernatur sunt porro, voluptate libero excepturi explicabo nulla maiores in similique, vel praesentium.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius nam assumenda aspernatur, numquam exercitationem eos delectus enim odit provident explicabo. Temporibus sunt labore laboriosam praesentium cumque. Dolorem iste labore cupiditate?</p>
      </div>
    </div>
  )
}
